
server:
  port: 3000

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect:
        format_sql:
    show-sql: true
  main:
    web-application-type: servlet

